name: Code Quality

on:
  pull_request:
    types: [opened, reopened]

jobs:
  pre-commit:
    name: Linting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0
