name: Test

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        poetry-version: [1.1.5]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Run tests
        run: bazel test tests
