name: Test

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Install apt deps
        run: sudo apt-get install -y libgl1 python3.8-dev

      - name: Run tests
        run: bazel test tests --test_output=errors
