name: Release

# on:
#   push:
#     tags:
#       - '*.*.*'

on: [push]

jobs:
  Release:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        poetry-version: [1.1.5]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Build project for distribution
        run: poetry build

      - name: Check Version
        id: check-version
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
            || echo ::set-output name=prerelease::true

      # - name: Create Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "dist/*"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     draft: false
      #     prerelease: steps.check-version.outputs.prerelease == 'true'

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish
